micronaut-projects/micronaut-kafka

kafka/src/main/java/io/micronaut/configuration/kafka/health/KafkaHealthIndicator.java
Use the property 'offsets.topic.replication.factor' instead of  'transaction.state.log.replication.factory' because this is the only one that are needed to be set to one in case of a one node cluster.
This allow health check with a one node cluster to works.
This fixes #11
=> fix: use offset topic replication instead of transaction one

src/main/docs/guide/kafkaQuickStart.adoc
Add an exemple of SSL configuration for Kafka broker.
This is a very common configuration and it's not easy to find by ourselves without documentation.
=> feat: add SSL configuration exemple

kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/errors/KafkaErrorHandlingSpec.groovy
This change breaks out of the poll loop and prevents committing offset on exception, that allows a custom exception handler to then seek back and resume the original message consumption avoiding message loss.
=>  Break out of poll() loop on exception. Fixes #39

src/main/docs/guide/kafkaApplications/kafkaMetrics.adoc
The kafka metric configuration refers to `MeterRegistryFactory.MICRONAUT_METRICS_BINDERS`:
https://github.com/micronaut-projects/micronaut-kafka/blob/1bc9749274ff759abe7c578c4cfc6c662f9cc6ed/kafka/src/main/java/io/micronaut/configuration/kafka/metrics/KafkaConsumerMetrics.java#L41
Here is the relevant snippet from `io.micronaut.configuration.metrics.micrometer.MeterRegistryFactory`:
```
public static final String MICRONAUT_METRICS = "micronaut.metrics.";
public static final String MICRONAUT_METRICS_BINDERS = MICRONAUT_METRICS + "binders";
```
https://github.com/micronaut-projects/micronaut-micrometer/blob/master/micrometer-core/src/main/java/io/micronaut/configuration/metrics/micrometer/MeterRegistryFactory.java#L42
So the configuration needs to include `binders` for it to be picked up.
=> Kafka metrics enabled config Documentation

gradle.properties, kafka/src/main/java/io/micronaut/configuration/kafka/annotation/KafkaListener.java, kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/annotation/KafkaUniqueGroupIdSpec.groovy, src/main/docs/guide/kafkaListener/kafkaListenerConfiguration.adoc
This allows to make sure consumer instances are - when needed - in different consumer groups
Refs #38
=> Extend KafkaListener annotation to define unique group ids

kafka/src/main/java/io/micronaut/configuration/kafka/intercept/KafkaClientIntroductionAdvice.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/annotation/KafkaClientSpec.groovy, kafka/src/test/groovy/io/micronaut/configuration/kafka/annotation/KafkaProducerSpec.groovy, src/main/docs/guide/kafkaClient/kafkaClientMethods.adoc
- Added ability to pass `Collection<org.apache.kafka.common.header.Header>` to `@KafkaClient` interface methods
- Added ability to pass `org.apache.kafka.common.header.Headers` to `@KafkaClient` interface methods
=> @KafkaClient Header and Headers Argument Enhancements

kafka-streams/src/test/resources/logback.xml, kafka/src/main/java/io/micronaut/configuration/kafka/annotation/KafkaListener.java, kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java
This reverts commit 0561addba7a0f7366b0aa6a0fd735f8f180bc064.
Fixes #190
=> Revert "Ensure KafkaConsumerProcessor is initialized before polling"

src/main/docs/guide/kafkaStreams.adoc
I might have gone a bit too far with the examples. I just want to cover the case where Micronaut - creates the `default `stream by default. Covering the following case:
If you have 1 micronaut service and you define 1 single Kstream definition, but on the configuration you dont use the key `kafka.streams.default` but instead you do` kafka.streams.<STREAM_NAME>` then Micronaut will spin your Stream but at the same time it will try to spin a default stream which obviously will result to exceptions and errors.
=> Documentation - Update on Configuring Kafka Streams section

kafka-streams/src/main/java/io/micronaut/configuration/kafka/streams/health/KafkaStreamsHealth.java, kafka-streams/src/test/groovy/io/micronaut/configuration/kafka/streams/health/KafkaStreamsHealthDisabledSpec.groovy, src/main/docs/guide/kafkaApplications/kafkaHealth.adoc, src/main/docs/guide/kafkaStreams/kafkaStreamHealth.adoc
changed `kafka.streams.health.enabled` to `kafka.health.streams.enabled` to avoid creating a stream called "health"
Fixes https://github.com/micronaut-projects/micronaut-kafka/issues/196
=> Fix disabling kafka-streams health check

kafka-streams/src/main/java/io/micronaut/configuration/kafka/streams/InteractiveQueryService.java
This removes usage of the `KafkaStreams.store(String, QueryableStoreType)` in favor of `store(StoreQueryParameters)`, as recommended in the kafka streams code:
=> Remove deprecated kafka streams store api usage

kafka/src/main/java/io/micronaut/configuration/kafka/package-info.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/docs/producer/fallback/MessageClient.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/docs/producer/fallback/MessageClientFallback.java, kafka/src/test/groovy/io/micronaut/test/DisabledClient.java, kafka/src/test/groovy/io/micronaut/test/DisabledClientFallback.java, kafka/src/test/groovy/io/micronaut/test/DisabledConsumer.java, kafka/src/test/groovy/io/micronaut/test/DisabledSpec.groovy, src/main/docs/guide/kafkaApplications/kafkaDisabled.adoc, src/main/docs/guide/toc.yml
As requested in https://github.com/micronaut-projects/micronaut-kafka/pull/211, this has been rewritten to apply the `@Requires` annotation at the `package-info.java` level.
A couple of notes:
- Without providing replacement beans for `@KafkaClient` interfaces, you get startup failures: `Caused by: java.lang.IllegalStateException: At least one @Introduction method interceptor required, but missing.`, which isn't particularly helpful, so I've added instructions to the docs
- I had to write my tests in a different package (`io.micronaut.test`), as otherwise they were affected by the `package-info.java` change
- I wrote my test fixture classes as separate .java files, as for some reason I kept hitting this exception whenever I tried to implement one of my `@KafkaClient` interfaces in groovy: …
=> Allow micronaut-kafka to be globally disabled

kafka/src/main/java/io/micronaut/configuration/kafka/ConsumerRegistry.java, kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/annotation/ConsumerRegistrySpec.groovy
Expose each consumer's subscriptions and assignment through the `ConsumerRegistry` keyed by client id.  This information is hard to get since it can only be accessed from poll loop thread.
=> Expose Consumer Assignment through ConsumerRegistry

kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java
* Reduce cognitive complexity in `KafkaConsumerProcessor.process` by breaking up into smaller methods
* Reduce compiler / linter warnings
Did some refactoring to break up the functionality within the class into smaller bite-size pieces of code.
=> Refactor KafkaConsumerProcessor

build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties, kafka-streams/src/main/java/io/micronaut/configuration/kafka/streams/ConfiguredStreamBuilder.java, kafka/src/main/java/io/micronaut/configuration/kafka/ConsumerAware.java, kafka/src/main/java/io/micronaut/configuration/kafka/ConsumerRegistry.java, kafka/src/main/java/io/micronaut/configuration/kafka/KafkaConsumerAware.java, kafka/src/main/java/io/micronaut/configuration/kafka/KafkaProducerRegistry.java, kafka/src/main/java/io/micronaut/configuration/kafka/ProducerRegistry.java, kafka/src/main/java/io/micronaut/configuration/kafka/bind/KafkaHeaderBinder.java, kafka/src/main/java/io/micronaut/configuration/kafka/bind/KafkaMessageHeaderBinder.java, kafka/src/main/java/io/micronaut/configuration/kafka/config/AbstractKafkaConfiguration.java, kafka/src/main/java/io/micronaut/configuration/kafka/config/AbstractKafkaConsumerConfiguration.java, kafka/src/main/java/io/micronaut/configuration/kafka/config/AbstractKafkaProducerConfiguration.java, kafka/src/main/java/io/micronaut/configuration/kafka/embedded/KafkaEmbeddedConfiguration.java, kafka/src/main/java/io/micronaut/configuration/kafka/exceptions/DefaultKafkaListenerExceptionHandler.java, kafka/src/main/java/io/micronaut/configuration/kafka/intercept/KafkaClientIntroductionAdvice.java, kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java, kafka/src/main/java/io/micronaut/configuration/kafka/scope/KafkaClientScope.java, kafka/src/main/java/io/micronaut/configuration/kafka/serde/CompositeSerdeRegistry.java, kafka/src/main/java/io/micronaut/configuration/kafka/tracing/brave/BraveKafkaTracingFactory.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/annotation/KafkaBatchListenerSpec.groovy, kafka/src/test/groovy/io/micronaut/configuration/kafka/annotation/KafkaListenerSpec.groovy, kafka/src/test/groovy/io/micronaut/configuration/kafka/docs/consumer/offsets/rebalance/ProductListener.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/docs/producer/headers/ProductClient.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/health/KafkaConsumerMetricsSpec.groovy, kafka/src/test/groovy/io/micronaut/configuration/kafka/health/KafkaProducerMetricsSpec.groovy
=> Fix handling of non-deprecated annotations

kafka/src/main/java/io/micronaut/configuration/kafka/annotation/KafkaPartition.java, kafka/src/main/java/io/micronaut/configuration/kafka/annotation/KafkaPartitionKey.java, kafka/src/main/java/io/micronaut/configuration/kafka/bind/KafkaPartitionBinder.java, kafka/src/main/java/io/micronaut/configuration/kafka/intercept/KafkaClientIntroductionAdvice.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/AbstractKafkaContainerSpec.groovy, kafka/src/test/groovy/io/micronaut/configuration/kafka/annotation/KafkaPartitionSpec.groovy
Hi all,
Although I haven't faced this need in micronaut projects yet, I have found it potentially useful to control partitioning separately from record keys.
This is useful when Keys have specific functional requirement (deduplication, log compaction, etc), but where partitioning of a topic needs to be made on a separate field (often having a one to many relationship with record keys, although that's not a requirement).
This PR brings in the ability to do just that with two new additional annotations: `@KafkaPartition` and `@KafkaPartitionKey`.
=> Add KafkaPartition and KafkaPartitionKey annotations

kafka/src/main/resources/META-INF/native-image/io.micronaut.kafka/micronaut-kafka/native-image.properties
This PR fixes the following warnings during native image creation
```
...
...
Warning: class initialization of class io.micronaut.configuration.kafka.health.$KafkaHealthIndicator$Definition failed with exception java.lang.NoClassDefFoundError: io/micronaut/management/health/indicator/HealthIndicator. This class will be initialized at run time because option --allow-incomplete-classpath is used for image building. Use the option --initialize-at-run-time=io.micronaut.configuration.kafka.health.$KafkaHealthIndicator$Definition to explicitly request delayed initialization of this class.
Warning: class initialization of class io.micronaut.configuration.kafka.tracing.$KafkaConsumerTracingInstrumentation$Definition failed with exception java.lang.NoClassDefFoundError: io/opentracing/Tracer. This …
```
=> Fix GraalVM warnings

kafka/src/main/java/io/micronaut/configuration/kafka/ConsumerRegistry.java, kafka/src/main/java/io/micronaut/configuration/kafka/annotation/ErrorStrategy.java, kafka/src/main/java/io/micronaut/configuration/kafka/annotation/ErrorStrategyValue.java, kafka/src/main/java/io/micronaut/configuration/kafka/annotation/KafkaListener.java, kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/AbstractKafkaSpec.groovy, kafka/src/test/groovy/io/micronaut/configuration/kafka/errors/KafkaErrorStrategySpec.groovy, kafka/src/test/groovy/io/micronaut/configuration/kafka/errors/KafkaErrorsSpec.groovy, kafka/src/test/groovy/io/micronaut/configuration/kafka/errors/KafkaShutdownHandlingSpec.groovy, src/main/docs/guide/kafkaListener/kafkaErrors.adoc, src/main/docs/guide/kafkaListener/kafkaExceptions.adoc, src/main/docs/guide/toc.yml
Fixes #372
Fixes #315 Replaces https://github.com/micronaut-projects/micronaut-kafka/pull/413
+ Refactoring of consumer implementation, extracting one consumer state bean and synchronizing on its state.
=> Commit successful records on error

src/main/docs/guide/kafkaListener/kafkaErrors.adoc
KafkaErrors.adoc incorrectly includes `RETRY_ON_ERROR` error strategy twice. Updates second to `RESUME_AT_NEXT_RECORD`
=> Fix Incorrect Error Strategy Item in KafkaErrors.adoc

kafka/src/main/java/io/micronaut/configuration/kafka/KafkaMessage.java, kafka/src/main/java/io/micronaut/configuration/kafka/KafkaProducerFactory.java, kafka/src/main/java/io/micronaut/configuration/kafka/Message.java, kafka/src/main/java/io/micronaut/configuration/kafka/TransactionalProducerRegistry.java, kafka/src/main/java/io/micronaut/configuration/kafka/annotation/KafkaClient.java, kafka/src/main/java/io/micronaut/configuration/kafka/annotation/KafkaListener.java, kafka/src/main/java/io/micronaut/configuration/kafka/annotation/OffsetStrategy.java, kafka/src/main/java/io/micronaut/configuration/kafka/intercept/KafkaClientIntroductionAdvice.java, kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/KafkaTxSpec.groovy, kafka/src/test/groovy/io/micronaut/configuration/kafka/docs/consumer/sendto/WordCounter.java, src/main/docs/guide/kafkaClient.adoc, src/main/docs/guide/kafkaClient/kafkaClientTx.adoc, src/main/docs/guide/kafkaListener/kafkaListenerConfiguration.adoc, src/main/docs/guide/kafkaListener/kafkaOffsets.adoc, src/main/docs/guide/kafkaListener/kafkaSendTo.adoc, src/main/docs/guide/toc.yml, tests/tasks-sasl-plaintext/build.gradle
=> Kafka transactions

kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/errors/KafkaErrorHandlingSpec.groovy
Version 4.1.0 introduced a bug for reactive consumers, the `DefaultKafkaListenerExceptionHandler` is always used even when a bean implements its own `KafkaListenerExceptionHandler`.
The problem was introduced here https://github.com/micronaut-projects/micronaut-kafka/pull/441, there are a couple of calls to the `handleException()` that expects a `consumerBean` which are receiving a `consumerState`. Added a test to verify that the simple fix works.
cc @dstepanov
=> Fix exception handling for reactive consumers

src/main/docs/guide/kafkaListener/kafkaListenerMethods.adoc
The link was pointing to the kafka repo, but this annotation is defined in the core repo.
Fixes https://github.com/micronaut-projects/micronaut-kafka/issues/381
Duplicate of #382 to try and get the actions to run
=> Fix broken @blocking link

gradle/libs.versions.toml
We used to declare managed-kafka in the core catalog.  We want to remove this for ease of
maintenance, but this means we would break compatibility as here it's managed-kafka-clients.
This PR adds a temporary duplication of the catalog to keep managed-kafka in the catalog here
This can be removed for 4.0.0
Removal was here https://github.com/micronaut-projects/micronaut-core/pull/7123
=> Duplicate managed-kafka depenedency for core compatibility

buildSrc/src/main/groovy/io.micronaut.build.internal.kafka-module.gradle
This an attempt to solve: 
https://github.com/micronaut-projects/micronaut-kafka/runs/7275178598?check_suite_focus=true
```
import org.graalvm.nativeimage.hosted.Feature;
[84](https://github.com/micronaut-projects/micronaut-kafka/runs/7275178598?check_suite_focus=true#step:10:85)
^
[85](https://github.com/micronaut-projects/micronaut-kafka/runs/7275178598?check_suite_focus=true#step:10:86)
bad class file: /home/runner/.gradle/caches/modules-2/files-2.1/org.graalvm.sdk/graal-sdk/22.1.0.1/dbdb86af102a25d64a59b828937894576a5700d1/graal-sdk-22.1.0.1.jar(org/graalvm/nativeimage/hosted/Feature.class)
[86](https://github.com/micronaut-projects/micronaut-kafka/runs/7275178598?check_suite_focus=true#step:10:87)
class file has wrong version 55.0, should be 52.0
```
=> build: pin graal-sdk

gradle.properties
https://github.com/micronaut-projects/micronaut-core/wiki/Module-Upgrade-Strategy
> A major version of the module will be included in a minor version of Micronaut only if we are sure that the change will not introduce breaking changes in users apps.
We think updating from Kafka 2 to Kafka 3 may break user applications
[ci skip]
=> build: target Micronaut 4.0.x

kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/errors/KafkaPartitionedErrorsSpec.groovy
This makes the `close()` method of `KafkaConsumerProcessor` wait for all
consumers to be properly closed
Refs #601
=> Fix kafka consumer shutdown

kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/errors/KafkaErrorStrategySpec.groovy, settings.gradle
Fixes https://github.com/micronaut-projects/micronaut-kafka/issues/610 which is caused by a retried record and rebalance occuring simultaneously, e.g. if the record handler both takes too long, and throws an exception.
Because assignments are only updated on calls to poll(), I don't believe it is possible to respect the RETRY_DELAY via the pause() mechanism that the retry logic currently uses.
=> [#610] Dont pause unassigned TopicPartitions

kafka/src/main/java/io/micronaut/configuration/kafka/annotation/ErrorStrategy.java, kafka/src/main/java/io/micronaut/configuration/kafka/annotation/ErrorStrategyValue.java, kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/errors/KafkaErrorStrategySpec.groovy
=> GH-604: Introduce exponential backoff for ErrorStrategy retry delay

src/main/docs/guide/kafkaClient/kafkaClientConfiguration.adoc, src/main/docs/guide/kafkaListener.adoc
A colleague and I had some issues figuring out how to apply custom bootstrap server configs for different `@KafkaClient` instances. Once we figured out the intended way to do it, I figured we should add some docs on it.
=> Improve docs for `@KafkaClient`/`@KafkaListener` behavior

kafka/src/main/java/io/micronaut/configuration/kafka/metrics/builder/KafkaMetricMeterType.java, kafka/src/main/java/io/micronaut/configuration/kafka/metrics/builder/KafkaMetricMeterTypeBuilder.java, kafka/src/main/java/io/micronaut/configuration/kafka/metrics/builder/KafkaMetricMeterTypeRegistry.java
Fixed #648 and #671
Fixes exceptions like this:
```
WARN [0;39m [35mi.m.c.i.internal.DefaultGauge[0;39m - Failed to apply the value function for the gauge 'kafka.producer.commit-id'. Note that subsequent logs will be logged at debug level.
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Number (java.lang.String and java.lang.Number are in module java.base of loader 'bootstrap')
at io.micronaut.configuration.kafka.metrics.builder.KafkaMetricMeterTypeBuilder.lambda$build$0(KafkaMetricMeterTypeBuilder.java:137)
at io.micrometer.core.instrument.Gauge.lambda$builder$0(Gauge.java:58)
at io.micrometer.core.instrument.StrongReferenceGaugeFunction.applyAsDouble(StrongReferenceGaugeFunction.java:48)
at …
```
=> Skip string metrics (like these: 'kafka.producer.commit-id', 'version', 'commitId', 'applicationId', 'topologyDescription')

kafka/src/main/java/io/micronaut/configuration/kafka/annotation/OffsetStrategy.java
The documentation for `SYNC_PER_RECORD` and `ASYNC_PER_RECORD` were out of sync with other messaging. This change aligns the wording with the wording used in `SYNC` and `ASYNC` as well as with the official documentation for the micronaut-kafka module using the term "processed" to mean after a KafkaListener handles and acts on a ConsumerRecord.
official documentation: https://micronaut-projects.github.io/micronaut-kafka/4.5.2/guide/#kafkaOffsets
This also clarifies that the implementation calls Kafka commit methods AFTER a message is processed as defined by the current implementation
https://github.com/micronaut-projects/micronaut-kafka/blob/b5c9ebb1f9df6679a3b49ac874616ec1ff59444c/kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java#LL515-L562C10
=> docs(OffsetStrategy): align with docs and implementation

kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/docs/consumer/batch/BookListener.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/docs/consumer/batch/ack/BookListener.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/docs/consumer/batch/manual/BookListener.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/docs/consumer/offsets/ack/ProductListener.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/offsets/BatchManualAckSpec.groovy, src/main/docs/guide/kafkaListener/kafkaListenerBatch.adoc, src/main/docs/guide/kafkaListener/kafkaOffsets.adoc
Add support for an `Acknowledgement` parameter in batch `KafkaListener` methods. Addresses Issue #54
Update docs for consistency between one-by-one processing and batch, including linking to the correct 
`Acknowledgement` class reference from the Micronaut messaging package.
=> Add support for batch Acknowledgement. (#54)

kafka/src/main/java/io/micronaut/configuration/kafka/bind/batch/BatchConsumerRecordsBinderRegistry.java
`findArgumentBinder(io.micronaut.core.type.Argument<T>, S)` is deprecated and marked for removal
=> Replace deprecated method call `findArgumentBinder`

kafka/src/main/java/io/micronaut/configuration/kafka/health/KafkaHealthIndicator.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/health/KafkaHealthIndicatorSpec.groovy
=> Kafka health checks and topics replication

kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/errors/KafkaErrorStrategySpec.groovy
=> Catch record deserialization exceptions that may happen while polling

gradle.properties, kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java, test-suite-groovy/src/test/groovy/io/micronaut/kafka/docs/MyTest.groovy, test-suite-kotlin/src/test/kotlin/io/micronaut/kafka/docs/MyTest.kt, test-suite/src/test/java/io/micronaut/kafka/docs/MyTest.java
Steps to reproduce the problem:
- A unit test must create a singleton kafka container.
- There must be some kafka consumer in the application context.
Example:
```java
@MicronautTest
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class MyTest implements TestPropertyProvider {
static final KafkaContainer MY_KAFKA = new KafkaContainer(DockerImageName.parse("confluentinc/cp-kafka:latest"));
static { MY_KAFKA.start(); }
@Override
public Map<String, String> getProperties() {
return Map.of("kafka.bootstrap.servers", MY_KAFKA.getBootstrapServers());
}
@Test
void testKafkaRunning(MyProducer producer) {
producer.produce("hello");
}
@KafkaClient interface MyProducer {
@Topic("my-topic")
void produce(String message);
}
@KafkaListener static class MyConsumer {
@Topic("my-topic")
public void …
```
=> CI never ends for unit tests with manual test container lifecycle control

kafka-streams/src/main/java/io/micronaut/configuration/kafka/streams/event/AbstractKafkaStreamsEvent.java, kafka/src/main/java/io/micronaut/configuration/kafka/event/AbstractKafkaApplicationEvent.java, kafka/src/main/java/io/micronaut/configuration/kafka/event/KafkaConsumerStartedPollingEvent.java, kafka/src/main/java/io/micronaut/configuration/kafka/event/KafkaConsumerSubscribedEvent.java, kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/event/KafkaConsumerEventSpec.groovy
Provides a solution for https://github.com/micronaut-projects/micronaut-kafka/issues/457
=> Publish events after Consumer subscribes and after first polling

kafka/src/main/java/io/micronaut/configuration/kafka/metrics/builder/KafkaMetricMeterTypeBuilder.java
Related to: 
- https://github.com/micronaut-projects/micronaut-kafka/issues/671
- https://github.com/micronaut-projects/micronaut-kafka/pull/668
Addresses the following:
```
05:06:46.307 [elastic-apm-shared] WARN  io.micrometer.core.instrument.internal.DefaultGauge - Failed to apply the value function for the gauge 'kafka.consumer.commit-id'. Note that subsequent logs will be logged at debug level.
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Number (java.lang.String and java.lang.Number are in module java.base of loader 'bootstrap')
at io.micronaut.configuration.kafka.metrics.builder.KafkaMetricMeterTypeBuilder.lambda$build$0(KafkaMetricMeterTypeBuilder.java:137) ~[XXX.jar:?]
at io.micrometer.core.instrument.Gauge.lambda$builder$0(Gauge.java:58) …
```
=> Safely destructure numerical values when configuring Kafka Metrics

kafka/src/test/groovy/io/micronaut/configuration/kafka/docs/consumer/batch/BookListener.java, src/main/docs/guide/kafkaListener/kafkaListenerBatch.adoc
Kafka batch listeners don't work as it's currently described in the documentation.
=> Fix outdated documentation for Kafka batch listeners

kafka/src/test/groovy/docs/producer/fallback/MessageClient.java, kafka/src/test/groovy/docs/producer/fallback/MessageClientFallback.java, kafka/src/test/groovy/docs/producer/fallback/MessageClientFallbackSpec.groovy, kafka/src/test/groovy/io/micronaut/configuration/kafka/docs/producer/fallback/MessageClientFallback.java, src/main/docs/guide/kafkaApplications/kafkaDisabled.adoc
The class needs to be annotated with @Singleton so that it can be injected
=> Missing @Singleton

kafka/src/main/java/io/micronaut/configuration/kafka/intercept/KafkaClientIntroductionAdvice.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/annotation/KafkaProducerSpec.groovy
While looking into #52, I realized Kafka producers can't handle `ProducerRecord` objects properly at the moment.
Since consumers can receive `ConsumerRecord` objects, I thought producers should be able to send `ProducerRecord` objects for the sake of symmetry.
This implementation works for both modes batch/single. Fields not populated by the user may be populated by the context as usual.
```java
@KafkaClient
interface SingleProducer {
@Topic("foo")
String sendRecord(ProducerRecord<String, String> record);
}
@KafkaClient(batch = true)
interface BatchProducer {
@Topic("foo")
String sendRecords(List<ProducerRecord<String, String>> records);
}
```
=> Decorate user-provided instances of `ProducerRecord`, instead of using them as a raw values

kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java, kafka/src/test/resources/logback.xml
While investigating #557, I came across this nagging TRACE message that keeps polluting my logs:
```
TRACE i.m.c.k.p.KafkaConsumerProcessor - consumer not closed yet
TRACE i.m.c.k.p.KafkaConsumerProcessor - consumer not closed yet
TRACE i.m.c.k.p.KafkaConsumerProcessor - consumer not closed yet
...
```
I've made some changes to limit how often we log this message while we're actively waiting for a consumer to close.
=> Avoid log pollution while waiting for consumer to close

buildSrc/src/main/groovy/io.micronaut.internal.build.kafka-testsuite.gradle, gradle/libs.versions.toml, test-suite-groovy/build.gradle.kts, test-suite-groovy/src/test/groovy/io/micronaut/kafka/docs/quickstart/QuickStartTest.groovy, test-suite-kotlin/build.gradle.kts, test-suite-kotlin/src/test/kotlin/io/micronaut/kafka/docs/AbstractKafkaTest.kt, test-suite-kotlin/src/test/kotlin/io/micronaut/kafka/docs/MyTest.kt, test-suite-kotlin/src/test/kotlin/io/micronaut/kafka/docs/quickstart/QuickstartTest.kt, test-suite/build.gradle.kts, test-suite/src/test/java/io/micronaut/kafka/docs/AbstractKafkaTest.java, test-suite/src/test/java/io/micronaut/kafka/docs/MyTest.java, test-suite/src/test/java/io/micronaut/kafka/docs/quickstart/QuickstartTest.java
except for `MyTest` used by docs as example for using Testcontainers directly.
=> Fixing test-suite docs examples to use test-resources

kafka/src/main/java/io/micronaut/configuration/kafka/health/KafkaHealthIndicator.java
`KafkaHealthIndicator` should no longer express an unconditional requirement for `AdminClient`.
=> Remove obsolete bean requirement `KafkaHealthIndicator` -> `AdminClient`

buildSrc/src/main/groovy/io.micronaut.internal.build.kafka-testsuite.gradle, gradle/libs.versions.toml, kafka/build.gradle, kafka/src/main/java/io/micronaut/configuration/kafka/intercept/KafkaClientIntroductionAdvice.java, kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/annotation/KafkaBatchListenerSpec.groovy, kafka/src/test/groovy/io/micronaut/configuration/kafka/annotation/KafkaListenerSpec.groovy, kafka/src/test/groovy/io/micronaut/configuration/kafka/annotation/KafkaReactiveListenerSpec.groovy, kafka/src/test/groovy/io/micronaut/configuration/kafka/annotation/KafkaSendToSpec.groovy, kafka/src/test/groovy/io/micronaut/configuration/kafka/health/KafkaProducerMetricsSpec.groovy, settings.gradle, src/main/docs/guide/kafkaClient/kafkaClientBatch.adoc, src/main/docs/guide/kafkaClient/kafkaClientMethods.adoc, src/main/docs/guide/kafkaListener/kafkaListenerBatch.adoc, src/main/docs/guide/kafkaListener/kafkaListenerMethods.adoc, test-suite-groovy/src/test/groovy/io/micronaut/kafka/docs/consumer/batch/BookClient.groovy, test-suite-groovy/src/test/groovy/io/micronaut/kafka/docs/consumer/reactive/ProductListener.groovy, test-suite-groovy/src/test/groovy/io/micronaut/kafka/docs/producer/methods/BookClient.groovy, test-suite-kotlin/src/test/kotlin/io/micronaut/kafka/docs/consumer/batch/BookClient.kt, test-suite-kotlin/src/test/kotlin/io/micronaut/kafka/docs/consumer/reactive/ProductListener.kt, test-suite-kotlin/src/test/kotlin/io/micronaut/kafka/docs/producer/methods/BookClient.kt, test-suite/src/test/java/io/micronaut/kafka/docs/consumer/batch/BookClient.java, test-suite/src/test/java/io/micronaut/kafka/docs/consumer/reactive/ProductListener.java, test-suite/src/test/java/io/micronaut/kafka/docs/producer/methods/BookClient.java
=> use reactor instead of rxjava2

kafka/src/main/java/io/micronaut/configuration/kafka/KafkaProducerFactory.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/KafkaTxSpec.groovy
=> Honor `transactionalId` when a Kafka producer bean is injected

kafka/src/main/java/io/micronaut/configuration/kafka/annotation/ErrorStrategyValue.java, kafka/src/main/java/io/micronaut/configuration/kafka/processor/ConsumerCloseState.java, kafka/src/main/java/io/micronaut/configuration/kafka/processor/ConsumerInfo.java, kafka/src/main/java/io/micronaut/configuration/kafka/processor/ConsumerSeekAwareAdapter.java, kafka/src/main/java/io/micronaut/configuration/kafka/processor/ConsumerState.java, kafka/src/main/java/io/micronaut/configuration/kafka/processor/FluxCallback.java, kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java, kafka/src/main/java/io/micronaut/configuration/kafka/processor/MonoCallback.java, kafka/src/main/java/io/micronaut/configuration/kafka/processor/PartitionRetryState.java
I extracted some internal classes out of `KafkaConsumerProcessor` and split some methods into smaller ones.
=> Refactor `KafkaConsumerProcessor`

gradle/libs.versions.toml, kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java, test-suite-kotlin/build.gradle.kts, test-suite-kotlin/src/test/kotlin/io/micronaut/kafka/docs/MyTest.kt
Proposal to fix a bug where method.isSuspended() always returns false and thus excludes the possibility of using suspend consumer functions
=> Suspend @KafkaListener functions

kafka/src/main/java/io/micronaut/configuration/kafka/processor/ConsumerState.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/offsets/BatchManualAckSpec.groovy, src/main/docs/guide/kafkaListener/kafkaListenerBatch.adoc, src/main/docs/guide/kafkaListener/kafkaOffsets.adoc, test-suite-groovy/src/test/groovy/io/micronaut/kafka/docs/consumer/batch/BookListener.groovy, test-suite-groovy/src/test/groovy/io/micronaut/kafka/docs/consumer/batch/ack/BookListener.groovy, test-suite-groovy/src/test/groovy/io/micronaut/kafka/docs/consumer/batch/manual/BookListener.groovy, test-suite-kotlin/src/test/kotlin/io/micronaut/kafka/docs/consumer/batch/BookListener.kt, test-suite-kotlin/src/test/kotlin/io/micronaut/kafka/docs/consumer/batch/ack/BookListener.kt, test-suite-kotlin/src/test/kotlin/io/micronaut/kafka/docs/consumer/batch/manual/BookListener.kt, test-suite/src/test/java/io/micronaut/kafka/docs/consumer/batch/BookListener.java, test-suite/src/test/java/io/micronaut/kafka/docs/consumer/batch/ack/BookListener.java, test-suite/src/test/java/io/micronaut/kafka/docs/consumer/batch/manual/BookListener.java
Based on: https://github.com/micronaut-projects/micronaut-kafka/pull/692
=> Add support for batch Acknowledgement

kafka/src/main/java/io/micronaut/configuration/kafka/bind/batch/BatchConsumerRecordsBinderRegistry.java, kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/annotation/KafkaBatchListenerSpec.groovy, src/main/docs/guide/kafkaListener/kafkaListenerBatch.adoc, test-suite-groovy/src/test/groovy/io/micronaut/kafka/docs/consumer/batch/manual/BookListener.groovy, test-suite-kotlin/src/test/kotlin/io/micronaut/kafka/docs/consumer/batch/manual/BookListener.kt, test-suite/src/test/java/io/micronaut/kafka/docs/consumer/batch/manual/BookListener.java
See #903
The changes are:
- Bind arguments of `ConsumerRecords` type;
- Consider `ConsumerRecords` type when looking for the "body argument" to configure the correct key and value deserializers;
- Add a test;
=> Support for ConsumerRecords container type on batch processing

kafka/src/main/java/io/micronaut/configuration/kafka/health/KafkaHealthIndicator.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/health/KafkaHealthIndicatorSpec.groovy
When no kafka configuration is provided:
```
Error creating scheduled task for bean [HealthMonitorTask] Failed to inject value for parameter [defaultConfiguration] of class: io.micronaut.configuration.kafka.health.KafkaHealthIndicator
Message: No bean of type [io.micronaut.configuration.kafka.config.KafkaDefaultConfiguration] exists. The following matching beans are disabled by bean requirements: 
* Bean of type [io.micronaut.configuration.kafka.config.KafkaDefaultConfiguration] is disabled because: 
- Required property [kafka] with value [null] not present
```
=> fix: kafka health indicator requires kafka configuration

CONTRIBUTING.md, kafka/src/main/java/io/micronaut/configuration/kafka/annotation/ErrorStrategy.java, kafka/src/main/java/io/micronaut/configuration/kafka/annotation/ErrorStrategyValue.java, kafka/src/main/java/io/micronaut/configuration/kafka/processor/ConsumerState.java, kafka/src/main/java/io/micronaut/configuration/kafka/processor/ConsumerStateBatch.java, kafka/src/main/java/io/micronaut/configuration/kafka/processor/ConsumerStateSingle.java, kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java, kafka/src/main/java/io/micronaut/configuration/kafka/retry/ConditionalRetryBehaviourHandler.java, kafka/src/main/java/io/micronaut/configuration/kafka/retry/DefaultConditionalRetryBehaviourHandler.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/errors/KafkaBatchErrorStrategySpec.groovy, kafka/src/test/groovy/io/micronaut/configuration/kafka/errors/KafkaErrorStrategySpec.groovy, src/main/docs/guide/kafkaListener/kafkaErrors.adoc, test-suite-groovy/src/test/groovy/io/micronaut/kafka/docs/consumer/errors/ConditionalRetryListener.groovy, test-suite-kotlin/src/test/kotlin/io/micronaut/kafka/docs/consumer/errors/ConditionalRetryListener.kt, test-suite/src/test/java/io/micronaut/kafka/docs/consumer/errors/ConditionalRetryListener.java
Potential solution for https://github.com/micronaut-projects/micronaut-kafka/issues/947.
Adds `RETRY_CONDITIONALLY_ON_ERROR` and `RETRY_CONDITIONALLY_EXPONENTIALLY_ON_ERROR` listener error stratiegies to conditionally retry messages on error.
=> Add RETRY_CONDITIONALLY_ON_ERROR and RETRY_CONDITIONALLY_EXPONENTIALLY_ON_ERROR KafkaListener error strategies to conditionally retry messages

kafka/src/main/java/io/micronaut/configuration/kafka/processor/ConsumerState.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/errors/KafkaErrorStrategySpec.groovy, src/main/docs/guide/kafkaListener/kafkaErrors.adoc
Processing of `@KafkaListener` methods is enhanced to allow reactive consumer methods annotated with `@Blocking` to work the same as non-reactive consumer methods in conjunction with retry error strategies.
Resolves #967
=> Allow reactive consumer methods with error strategy

kafka-streams/src/main/java/io/micronaut/configuration/kafka/streams/AbstractKafkaStreamsConfiguration.java, kafka-streams/src/main/java/io/micronaut/configuration/kafka/streams/ConfiguredStreamBuilder.java, kafka-streams/src/main/java/io/micronaut/configuration/kafka/streams/DefaultKafkaStreamsConfiguration.java, kafka-streams/src/main/java/io/micronaut/configuration/kafka/streams/KafkaStreamsConfiguration.java, kafka-streams/src/main/java/io/micronaut/configuration/kafka/streams/KafkaStreamsFactory.java, kafka-streams/src/test/groovy/io/micronaut/configuration/kafka/streams/AbstractKafkaSpec.groovy, kafka-streams/src/test/groovy/io/micronaut/configuration/kafka/streams/AbstractTestContainersSpec.groovy, kafka-streams/src/test/groovy/io/micronaut/configuration/kafka/streams/CloseTimeoutKafkaStreamsSpec.groovy, kafka-streams/src/test/groovy/io/micronaut/configuration/kafka/streams/KafkaStreamsSpec.groovy, kafka-streams/src/test/resources/logback.xml, src/main/docs/guide/kafkaStreams.adoc
This pull request proposes a new option to customise how long we wait for each `KafkaStreams` to close, as a fix for #901.
If you have a better idea for the name of the option, please let me know. I was not sure whether to go with `kafka.streams.close-seconds` or `kafka.streams-close-seconds`.
=> Add option to customise close() wait (fixes #901)

src/main/docs/guide/kafkaApplications/kafkaMetrics.adoc
Add missing documentation for configuration to disable the Kafka Streams metrics.
=> Add missing doc for config to disable Kafka streams metrics
