micronaut-projects/micronaut-kafka

kafka/build.gradle, kafka/src/main/java/io/micronaut/configuration/kafka/health/KafkaHealthIndicator.java, kafka/src/main/java/io/micronaut/configuration/kafka/intercept/KafkaClientIntroductionAdvice.java, kafka/src/main/java/io/micronaut/configuration/kafka/metrics/AbstractKafkaMetrics.java, kafka/src/main/java/io/micronaut/configuration/kafka/metrics/KafkaConsumerMetrics.java, kafka/src/main/java/io/micronaut/configuration/kafka/metrics/KafkaMetricsReporter.java, kafka/src/main/java/io/micronaut/configuration/kafka/metrics/KafkaProducerMetrics.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/annotation/KafkaListenerSpec.groovy, kafka/src/test/groovy/io/micronaut/configuration/kafka/annotation/KafkaTypeConversionSpec.groovy, kafka/src/test/groovy/io/micronaut/configuration/kafka/health/KafkaConsumerMetricsSpec.groovy, kafka/src/test/groovy/io/micronaut/configuration/kafka/health/KafkaHealthIndicatorSpec.groovy, kafka/src/test/groovy/io/micronaut/configuration/kafka/health/KafkaProducerMetricsSpec.groovy, src/main/docs/guide/kafkaApplications/kafkaHealth.adoc
Splitting up the Consumer and Producer metrics
* Includes #16 
* Addresses #17
* Adding tests for metrics on kafka consumer and producer
=> Fixing Kafka Consumer and Producer metrics

kafka/src/main/java/io/micronaut/configuration/kafka/health/KafkaHealthIndicator.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/health/KafkaHealthIndicatorSpec.groovy, src/main/docs/guide/kafkaApplications/kafkaHealth.adoc
This addresses the ability to disable the health endpoint.  Addresses #15
=> Adding flag to disable kafka health

kafka/src/main/java/io/micronaut/configuration/kafka/metrics/AbstractKafkaMetrics.java, kafka/src/main/java/io/micronaut/configuration/kafka/metrics/AbstractKafkaMetricsReporter.java, kafka/src/main/java/io/micronaut/configuration/kafka/metrics/ConsumerKafkaMetricsReporter.java, kafka/src/main/java/io/micronaut/configuration/kafka/metrics/KafkaConsumerMetrics.java, kafka/src/main/java/io/micronaut/configuration/kafka/metrics/KafkaProducerMetrics.java, kafka/src/main/java/io/micronaut/configuration/kafka/metrics/ProducerKafkaMetricsReporter.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/annotation/KafkaListenerSpec.groovy, kafka/src/test/groovy/io/micronaut/configuration/kafka/health/KafkaConsumerMetricsSpec.groovy, kafka/src/test/groovy/io/micronaut/configuration/kafka/health/KafkaProducerMetricsSpec.groovy
=> Adding consumer and producer prefix to the metrics

kafka/src/main/java/io/micronaut/configuration/kafka/config/KafkaDefaultConfiguration.java, kafka/src/main/java/io/micronaut/configuration/kafka/metrics/AbstractKafkaMetricsReporter.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/KafkaConfigurationSpec.groovy
Added a fix so as to be able to read array / list fields using default conversion service.
=> Added the conversion of list fields - Fixes #26

gradle.properties, kafka-streams/src/main/java/io/micronaut/configuration/kafka/streams/InteractiveQueryService.java, kafka-streams/src/main/java/io/micronaut/configuration/kafka/streams/KafkaStreamsFactory.java, kafka-streams/src/test/groovy/io/micronaut/configuration/kafka/streams/InteractiveQueryServiceExample.java, kafka-streams/src/test/groovy/io/micronaut/configuration/kafka/streams/KafkaStreamsSpec.groovy, kafka-streams/src/test/groovy/io/micronaut/configuration/kafka/streams/WordCountStream.java, kafka-streams/src/test/resources/logback.xml, kafka/src/main/java/io/micronaut/configuration/kafka/health/KafkaHealthIndicator.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/annotation/KafkaListenerSpec.groovy, kafka/src/test/groovy/io/micronaut/configuration/kafka/health/KafkaConsumerMetricsSpec.groovy, kafka/src/test/groovy/io/micronaut/configuration/kafka/health/KafkaProducerMetricsSpec.groovy, src/main/docs/guide/kafkaStream.adoc
This pull request adds the interactive query service to retrieve items from a state store similar to spring cloud feature.  I have also removed some items in tests that were causing some flakiness around with items are wired up and metrics are available.
=> Adding interactive query service, examples, tests and docs

kafka/src/main/java/io/micronaut/configuration/kafka/bind/KafkaHeaderBinder.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/annotation/KafkaListenerSpec.groovy
Addressing https://github.com/micronaut-projects/micronaut-kafka/issues/51 to allow optional headers to be passed in as an Optional.
=> Support Optional headers in Kafka listener

kafka/src/main/java/io/micronaut/configuration/kafka/annotation/KafkaTimestamp.java, kafka/src/main/java/io/micronaut/configuration/kafka/intercept/KafkaClientIntroductionAdvice.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/annotation/KafkaTimestampSpec.groovy
Hello, @graemerocher. 
This PR closes #63.
Waiting for you comments!
=> Support custom timestamp for ProducerRecord. Closes #63

kafka/src/main/java/io/micronaut/configuration/kafka/intercept/KafkaClientIntroductionAdvice.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/annotation/KafkaProducerSpec.groovy
Tracing wasn't working for producers
=> Fix producer instrumentation

src/main/docs/guide/kafkaClient/kafkaClientConfiguration.adoc
=> Use Serializer class and not Deserializer class

kafka/src/main/java/io/micronaut/configuration/kafka/intercept/KafkaClientIntroductionAdvice.java, kafka/src/main/java/io/micronaut/configuration/kafka/metrics/AbstractKafkaMetrics.java, kafka/src/main/java/io/micronaut/configuration/kafka/metrics/AbstractKafkaMetricsReporter.java, kafka/src/main/java/io/micronaut/configuration/kafka/metrics/builder/KafkaMetricMeterType.java, kafka/src/main/java/io/micronaut/configuration/kafka/metrics/builder/KafkaMetricMeterTypeBuilder.java, kafka/src/main/java/io/micronaut/configuration/kafka/metrics/builder/KafkaMetricMeterTypeRegistry.java, kafka/src/main/java/io/micronaut/configuration/kafka/metrics/builder/MeterType.java, kafka/src/main/java/io/micronaut/configuration/kafka/metrics/builder/package-info.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/metrics/builder/KafkaMetricMeterTypeBuilderSpec.groovy, kafka/src/test/groovy/io/micronaut/configuration/kafka/metrics/builder/KafkaMetricMeterTypeRegistrySpec.groovy, kafka/src/test/groovy/io/micronaut/configuration/kafka/metrics/builder/KafkaMetricMeterTypeSpec.groovy, kafka/src/test/groovy/io/micronaut/configuration/kafka/metrics/builder/MeterTypeSpec.groovy
=> Adding typed metric builder

gradle.properties, kafka-streams/build.gradle, kafka-streams/src/main/java/io/micronaut/configuration/kafka/streams/KafkaStreamsFactory.java, kafka-streams/src/main/java/io/micronaut/configuration/kafka/streams/health/KafkaStreamsHealth.java, kafka-streams/src/test/groovy/io/micronaut/configuration/kafka/streams/AbstractTestContainersSpec.groovy, kafka-streams/src/test/groovy/io/micronaut/configuration/kafka/streams/KafkaStreamsSpec.groovy, kafka-streams/src/test/groovy/io/micronaut/configuration/kafka/streams/health/KafkaStreamsHealthDisabledSpec.groovy, kafka-streams/src/test/groovy/io/micronaut/configuration/kafka/streams/health/KafkaStreamsHealthSpec.groovy, kafka-streams/src/test/groovy/io/micronaut/configuration/kafka/streams/optimization/OptimizationListener.java, kafka-streams/src/test/groovy/io/micronaut/configuration/kafka/streams/wordcount/WordCountListener.java, kafka-streams/src/test/resources/application-test.yml, kafka-streams/src/test/resources/logback.xml, src/main/docs/guide/kafkaStreams/kafkaStream.adoc, src/main/docs/guide/kafkaStreams/kafkaStreamHealth.adoc, src/main/docs/guide/kafkaStreams/kafkaStreamInteractiveQuery.adoc, src/main/docs/guide/toc.yml
* fixes #120 
* fixes #132 for streams module
I had to downgrade the test container version due to issue with docker java container https://github.com/docker-java/docker-java/pull/1392
=> Adding health check for streams

kafka-streams/src/main/java/io/micronaut/configuration/kafka/streams/health/KafkaStreamsHealth.java, kafka-streams/src/test/groovy/io/micronaut/configuration/kafka/streams/health/KafkaStreamsHealthSpec.groovy, src/main/docs/guide/toc.yml
Adding some small cleanup items for the docs and flowable
=> Kafka streams health

build.gradle, gradle.properties, kafka/build.gradle
Fixes https://github.com/micronaut-projects/micronaut-kafka/issues/216
=> Update Kafka to v2.6

gradle.properties, kafka/src/main/java/io/micronaut/configuration/kafka/intercept/KafkaClientIntroductionAdvice.java
Should be merged after upgrade to the core version 2.1.0
=> Migrate advice to use InterceptedMethod API

kafka/src/main/java/io/micronaut/configuration/kafka/config/KafkaDefaultConfiguration.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/annotation/KafkaClientSpec.groovy
Fixes https://github.com/micronaut-projects/micronaut-kafka/issues/261
=> fix @Requires annotation

kafka/src/main/java/io/micronaut/configuration/kafka/health/KafkaHealthIndicator.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/health/KafkaHealthIndicatorSpec.groovy
Resolves https://github.com/micronaut-projects/micronaut-kafka/issues/201
Confluent Cloud hosted Kafka doesn't provide [offsets.topic.replication.factor](https://kafka.apache.org/documentation/#brokerconfigs_offsets.topic.replication.factor), so this will fallback to [default.replication.factor](https://kafka.apache.org/documentation/#brokerconfigs_default.replication.factor) if required.
I extracted this out as a method so that I could include a test for this functionality, I couldn't find a way to test it otherwise without requiring some pretty involved mocking.
If neither config item is found, Integer.MAX_VALUE will be returned to force the health status to down, instead of throwing a NullPointerException.
=> Handle Confluent Cloud in KafkaHealthIndicator

kafka/src/test/groovy/io/micronaut/configuration/kafka/KafkaConfigurationSpec.groovy
=> test to verify env props override app props

kafka/src/main/java/io/micronaut/configuration/kafka/config/AbstractKafkaConfiguration.java, kafka/src/main/java/io/micronaut/configuration/kafka/config/KafkaDefaultConfiguration.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/KafkaConfigurationSpec.groovy, src/main/docs/guide/kafkaQuickStart.adoc
Add new configuration property `kafka.enabled` which defaults to `true`, to be able to disable kafka in certain situations
=> Add the Ability to Disable Kafka

kafka/src/main/resources/META-INF/native-image/io.micronaut/micronaut-kafka/native-image.properties, kafka/src/main/resources/META-INF/native-image/io.micronaut/micronaut-kafka/reflect-config.json, kafka/src/main/resources/META-INF/native-image/io.micronaut/micronaut-kafka/resource-config.json
=> Add native image flags

build.gradle, gradle.properties, kafka-streams/build.gradle, kafka/build.gradle, kafka/src/main/java/io/micronaut/configuration/kafka/graal/ByteBufferUnmapperSubstitute.java, kafka/src/main/java/io/micronaut/configuration/kafka/graal/SaslClientCallbackHandlerSubstitute.java, kafka/src/main/resources/META-INF/native-image/io.micronaut.kafka/micronaut-kafka/reflect-config.json, settings.gradle, tests/tasks-sasl-plaintext/build.gradle, tests/tasks-sasl-plaintext/src/main/java/example/Application.java, tests/tasks-sasl-plaintext/src/main/java/example/Task.java, tests/tasks-sasl-plaintext/src/main/java/example/TaskConstants.java, tests/tasks-sasl-plaintext/src/main/java/example/TasksController.java, tests/tasks-sasl-plaintext/src/main/java/example/TasksListener.java, tests/tasks-sasl-plaintext/src/main/java/example/TasksProducer.java, tests/tasks-sasl-plaintext/src/main/java/example/TasksPublisher.java, tests/tasks-sasl-plaintext/src/main/resources/application.yml, tests/tasks-sasl-plaintext/src/main/resources/logback.xml, tests/tasks-sasl-plaintext/src/test/groovy/example/TasksSpec.groovy, tests/tasks-sasl-plaintext/src/test/resources/example/kafka_server_jaas.conf
=> Support Sasl for GraalVM

kafka/src/main/resources/META-INF/native-image/io.micronaut.kafka/micronaut-kafka/native-image.properties
Fix attempt by removing the previous substituion
=> Fix GraalVM test

kafka/src/main/java/io/micronaut/configuration/kafka/ConsumerRegistry.java, kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java
Attempt to make it possible to pause and resume on topicPartition level
=> Pause / Resume a specified set of TopicPartitions instead of pausing the entire consumer 

kafka/src/main/java/io/micronaut/configuration/kafka/annotation/KafkaListener.java, kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/annotation/KafkaConsumerAutoStartupSpec.groovy
Fixes #372 
Branch based on another PR
=> Allow to start the listener paused on startup

.github/workflows/dependency-update.yml, README.md
changes from https://github.com/micronaut-projects/micronaut-kafka/pull/473 and https://github.com/micronaut-projects/micronaut-kafka/pull/477
=> more updates

src/main/docs/guide/kafkaCli.adoc
=> Fix documentation around producer and listener generation

kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/AbstractEmbeddedServerSpec.groovy, kafka/src/test/groovy/io/micronaut/configuration/kafka/AbstractKafkaContainerSpec.groovy, kafka/src/test/groovy/io/micronaut/configuration/kafka/errors/KafkaErrorsSpec.groovy, kafka/src/test/groovy/io/micronaut/configuration/kafka/errors/KafkaPartitionedErrorsSpec.groovy
=> Fix retries per partition

kafka-streams/src/main/java/io/micronaut/configuration/kafka/streams/health/KafkaStreamsHealth.java, kafka-streams/src/test/groovy/io/micronaut/configuration/kafka/streams/health/KafkaStreamsHealthSpec.groovy
Use details of all local threads instead of just the last one
=> Fix kafka-streams health details

kafka-streams/src/test/groovy/io/micronaut/configuration/kafka/streams/AbstractKafkaContainerSpec.groovy, kafka/src/test/groovy/io/micronaut/configuration/kafka/AbstractKafkaContainerSpec.groovy, kafka/src/test/groovy/io/micronaut/configuration/kafka/docs/DocTests.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/health/KafkaHealthIndicatorSpec.groovy, tests/tasks-sasl-plaintext/src/test/groovy/example/TasksSpec.groovy
That's one that works with arm
And the one we now pull for test resources
=> test: use cp-kafka 7.0.4

kafka-streams/build.gradle, kafka-streams/src/main/java/io/micronaut/configuration/kafka/streams/KafkaStreamsFactory.java, kafka-streams/src/main/java/io/micronaut/configuration/kafka/streams/metrics/KafkaStreamsMetrics.java, kafka-streams/src/main/java/io/micronaut/configuration/kafka/streams/metrics/KafkaStreamsMetricsReporter.java, kafka-streams/src/test/groovy/io/micronaut/configuration/kafka/streams/AbstractTestContainersSpec.groovy, kafka-streams/src/test/groovy/io/micronaut/configuration/kafka/streams/metrics/KafkaStreamsMetricsDisabledSpec.groovy, kafka-streams/src/test/groovy/io/micronaut/configuration/kafka/streams/metrics/KafkaStreamsMetricsSpec.groovy, kafka-streams/src/test/groovy/io/micronaut/configuration/kafka/streams/optimization/OptimizationStream.java, kafka-streams/src/test/groovy/io/micronaut/configuration/kafka/streams/wordcount/WordCountStream.java, kafka/src/main/java/io/micronaut/configuration/kafka/metrics/AbstractKafkaMetrics.java, kafka/src/main/java/io/micronaut/configuration/kafka/metrics/AbstractKafkaMetricsReporter.java, kafka/src/main/java/io/micronaut/configuration/kafka/metrics/KafkaProducerMetrics.java, kafka/src/main/java/io/micronaut/configuration/kafka/metrics/builder/KafkaMetricMeterTypeBuilder.java
- GH-347 kafka streams metrics
- Merge changes
- GH-347 fix checkstyle
- GH-347 undo metrics tag changes to put into separate PR
- fix test
=> GH 347 kafka streams metrics

kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/errors/KafkaShutdownHandlingSpec.groovy
- Test before the fix reproduce the issue
- Test pass after applying the fix
=> fix(#607): Kafka Listener committing whole batch on shutdown 

kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java
=> use the original group id for loading consumer configuration first

kafka/src/main/java/io/micronaut/configuration/kafka/annotation/ErrorStrategy.java, kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java, src/main/docs/guide/kafkaListener/kafkaErrors.adoc
=> Error Strategy retry on specifics exceptions

kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java
=> Fix graalvm issues with micronaut-kafka not working (4.5.x)

.github/workflows/graalvm.yml, settings.gradle, src/main/docs/guide/kafkaApplications/kafkaDisabled.adoc, src/main/docs/guide/kafkaApplications/kafkaHealth.adoc, src/main/docs/guide/kafkaApplications/kafkaMetrics.adoc, src/main/docs/guide/kafkaClient/kafkaClientConfiguration.adoc, src/main/docs/guide/kafkaClient/kafkaClientMethods.adoc, src/main/docs/guide/kafkaListener.adoc, src/main/docs/guide/kafkaListener/kafkaListenerConfiguration.adoc, src/main/docs/guide/kafkaQuickStart.adoc, src/main/docs/guide/kafkaStreams.adoc, src/main/docs/guide/kafkaStreams/kafkaStreamHealth.adoc
=> Migrate to new configuration asciidoc macro and build plugin 5.4.6

.gitattributes, kafka/src/main/resources/META-INF/native-image/io.micronaut.kafka/micronaut-kafka/native-image.properties, kafka/src/main/resources/META-INF/native-image/io.micronaut.kafka/micronaut-kafka/reflect-config.json, kafka/src/test/groovy/io/micronaut/configuration/kafka/AbstractKafkaContainerSpec.groovy, kafka/src/test/groovy/io/micronaut/configuration/kafka/annotation/KafkaProducerSpec.groovy, kafka/src/test/groovy/io/micronaut/configuration/kafka/docs/DocTests.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/health/KafkaHealthIndicatorSpec.groovy, tests/tasks-sasl-plaintext/src/test/groovy/example/TasksSpec.groovy
=> Added config for native build with OAuthBearer and SCRAM security protocols

kafka/src/main/java/io/micronaut/configuration/kafka/annotation/ErrorStrategy.java, kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/errors/KafkaErrorStrategySpec.groovy
=> Add new config property `ErrorStrategy.handleAllExceptions`

kafka/src/main/java/io/micronaut/configuration/kafka/annotation/ErrorStrategy.java, kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java, kafka/src/test/groovy/io/micronaut/configuration/kafka/errors/KafkaErrorStrategySpec.groovy, src/main/docs/guide/kafkaListener/kafkaErrors.adoc
=> Introduce `ErrorStrategy.retryCountValue` to allow for dynamic config

src/main/docs/guide/kafkaApplications/kafkaDisabled.adoc, test-suite-groovy/src/test/groovy/io/micronaut/kafka/docs/producer/fallback/MessageClient.groovy, test-suite-groovy/src/test/groovy/io/micronaut/kafka/docs/producer/fallback/MessageClientFallback.groovy, test-suite-groovy/src/test/groovy/io/micronaut/kafka/docs/producer/fallback/MessageClientFallbackSpec.groovy, test-suite-kotlin/src/test/kotlin/io/micronaut/kafka/docs/producer/fallback/MessageClient.kt, test-suite-kotlin/src/test/kotlin/io/micronaut/kafka/docs/producer/fallback/MessageClientFallback.kt, test-suite-kotlin/src/test/kotlin/io/micronaut/kafka/docs/producer/fallback/MessageClientFallbackTest.kt, test-suite/src/test/java/io/micronaut/kafka/docs/producer/fallback/MessageClient.java, test-suite/src/test/java/io/micronaut/kafka/docs/producer/fallback/MessageClientFallback.java, test-suite/src/test/java/io/micronaut/kafka/docs/producer/fallback/MessageClientFallbackTest.java
=> Multi-language documentation for fallback example

src/main/docs/guide/kafkaListener/kafkaListenerBatch.adoc, test-suite-groovy/build.gradle.kts, test-suite-groovy/src/test/groovy/io/micronaut/kafka/docs/consumer/batch/Book.groovy, test-suite-groovy/src/test/groovy/io/micronaut/kafka/docs/consumer/batch/BookListener.groovy, test-suite-kotlin/build.gradle.kts, test-suite-kotlin/src/test/kotlin/io/micronaut/kafka/docs/consumer/batch/Book.kt, test-suite-kotlin/src/test/kotlin/io/micronaut/kafka/docs/consumer/batch/BookListener.kt, test-suite/build.gradle.kts, test-suite/src/test/java/io/micronaut/kafka/docs/consumer/batch/Book.java, test-suite/src/test/java/io/micronaut/kafka/docs/consumer/batch/BookListener.java
=> Multi-language documentation for Committing Offsets Manually with Batch example

test-suite-groovy/build.gradle.kts, test-suite-groovy/src/test/groovy/io/micronaut/kafka/docs/AbstractKafkaTest.groovy, test-suite-groovy/src/test/groovy/io/micronaut/kafka/docs/MyTest.groovy, test-suite-groovy/src/test/groovy/io/micronaut/kafka/docs/quickstart/QuickStartTest.groovy, test-suite/src/test/java/io/micronaut/kafka/docs/MyTest.java
Remove awaitility
remove static container
stop stopping the container after tests
=> Groovify the groovy test-suite
